Add solution for 04.06 Query Sync
js-tasks-ru/vue-20210511_dmitriy29 pull request #19
Opened 2021-06-09 07:16 UTC by dvol79

2021-06-09 07:17 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-09 20:53 UTC, ShGKme requested changes
Требуется избавиться от отслеживания $data и переход на `path: '/'`. В остальном задача принята

2021-06-09 20:53 UTC, ShGKme commented on 04-spa/06-QuerySync/views/QuerySync.vue
> +    },
Отслеживать целиком `$data` - не очень хорошее решение. Так решение ориентируется на текущую реализацию, в которой в $data больше ничего нет. Это усложняет добавление новых свойств в компонент или переиспользование кода в других компонентах. Если хочется отслеживать все эти свойства, лучше хранить их в каком-нибудь локальном объекте, как свойства объекта, а не свойства сразу компонента.

Либо сделать 4 отслеживания с одинаковым handler-ом.

2021-06-09 20:53 UTC, ShGKme commented on 04-spa/06-QuerySync/views/QuerySync.vue
> +  },
`path` может быть не только `'/'`. Для изменения только query достаточно оставить в push объекте только query. Тогда остальные параметры маршрута изменены не будут.

2021-06-12 12:01 UTC, jsru commented
Добавляю преподавателя (@ShGKme) для код-ревью.

2021-06-12 12:10 UTC, ShGKme approved these changes
Принято 👍

2021-06-12 12:11 UTC, merged